### PR TITLE
Aligning with the example theme.

### PR DESCRIPTION
**Pull request by save-vi**
As suggested on the post merge discussion of the previous pull request.

### CODE REVIEW

**Comment by rantav** [comment]
LGTM, do you have comments @titusjaka ?

**Review by titusjaka — APPROVED** [review]
LGTM 👍

**Comment by VyacheslavIsaev** [comment]
I think it is a good  idea to squash it on merge... :)

**Comment by save-vi** [comment]
Just in case, I don't have rights to merge this pull request, so this is up to you guys to merge it...
Have a great week end!

**Comment by titusjaka** [comment]
Hi @save-vi 👋
Since you opened the PR from the master branch, it now includes commits that are not related to the topic. 
I will reopen the PR with the original commits and add you as a co-author 🤓

**Comment by save-vi** [comment]
Oh, yes, I was debugging homebrew tap for the project and didn't switched to another branch, so don't change the automation.
BTW, are you considering to create a private homebrew tap for the tool?
It turned out to be quite simple to automate publishing of homebrew formula updates with .goreleaser. Though, some configuration is required. :)

**Pull request closed without merging**
